version: "3.7"

services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres.gcgiowqadhayysmzgoai
      - POSTGRES_PASSWORD=Luis95112308084

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-enterprise-kafka:5.5.3
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 
    ports:
      - "9092:9092"

  create-transaction:
    container_name: create-transaction
    build: ./create-transaction
    ports:
      - "8080:8080"
    volumes:
      - ./create-transaction:/app
    environment:
      - PORT=8080
      - POSTGRES_URL=postgres://postgres.gcgiowqadhayysmzgoai:Luis95112308084@postgres:5432/POSTGRES_PASSWORD
      - HOST=aws-0-us-east-1.pooler.supabase.com
      - PASSWORD=Luis95112308084
      - USER=postgres.gcgiowqadhayysmzgoai
      - DATABASE=postgres
      - PORT=5432
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=topic1
    depends_on:
      - postgres
      - kafka

  retrieve-transaction:
    container_name: retrieve-transaction
    build: ./retrieve-transaction
    ports:
      - "8081:8081"
    volumes:
      - ./create-transaction:/app
    environment:
      - PORT=8081
      - POSTGRES_URL=postgres://postgres.gcgiowqadhayysmzgoai:Luis95112308084@postgres:5432/postgres
      - HOST=aws-0-us-east-1.pooler.supabase.com
      - PASSWORD=Luis95112308084
      - USER=postgres.gcgiowqadhayysmzgoai
      - DATABASE=postgres
      - PORT=5432
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=topic1
    depends_on:
      - postgres
      - kafka